name: Terraform Format Check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Show diff of unformatted files
        if: failure()
        run: terraform fmt -diff -recursive
