name: Terraform Security Code Scan tfsec

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
